### ISSUE TITLE
dhtxx 软件包添加后，编译报如下错误

### ISSUE THREAD

**Issue by qiaowei361** [luhuadong/rtt-dhtxx#1]
![image](https://user-images.githubusercontent.com/15102543/90135286-07e4d100-dda5-11ea-8c58-4126ce3d7028.png)

请作者解答一下，文档再详细一点，让我们更好的快速入门，谢谢

**Comment by luhuadong** [comment]
请更新一下 rt-thread 代码，或者手动更新 rt-thread/components/drivers/sensors，因为 packages 后面开发的，所以已发布的 rt-thread 版本不一定有相关信息。

**Comment by luhuadong** [comment]
至于文档，我抽时间好好整理一下。因为当时制作 dhtxx 软件包的目的是为了兼容所有单总线温湿度传感器，目前通过 dht_info 结构体传入具体的传感器类型：

```c
static int rt_hw_dht22_port(void)
{
    static struct dht_info info;
    struct rt_sensor_config cfg;

    info.type = DHT22;
    info.pin  = DHT22_DATA_PIN;
    
    cfg.intf.type = RT_SENSOR_INTF_ONEWIRE;
    cfg.intf.user_data = (void *)&info;
    rt_hw_dht_init("dh2", &cfg);
    
    return RT_EOK;
}
```

我在想要不要取消这种方式，改为通过 Kconfig 在 menuconfig 里配置，但是这样就不方便在一个设备上接入多个不同型号的温湿度传感器了。你觉得呢？

**Comment by qiaowei361** [comment]
> 至于文档，我抽时间好好整理一下。因为当时制作 dhtxx 软件包的目的是为了兼容所有单总线温湿度传感器，目前通过 dht_info 结构体传入具体的传感器类型：
> 
> ```c
> static int rt_hw_dht22_port(void)
> {
>     static struct dht_info info;
>     struct rt_sensor_config cfg;
> 
>     info.type = DHT22;
>     info.pin  = DHT22_DATA_PIN;
>     
>     cfg.intf.type = RT_SENSOR_INTF_ONEWIRE;
>     cfg.intf.user_data = (void *)&info;
>     rt_hw_dht_init("dh2", &cfg);
>     
>     return RT_EOK;
> }
> ```
> 
> 我在想要不要取消这种方式，改为通过 Kconfig 在 menuconfig 里配置，但是这样就不方便在一个设备上接入多个不同型号的温湿度传感器了。你觉得呢？

目前的框架结构还是不错的，感谢解答已经正常可以读取AM2320B，谢谢作者~
