### ISSUE TITLE
data pin number该如何设置？

### ISSUE THREAD

**Issue by bronya5th** [luhuadong/rtt-dhtxx#2]
作者你好，我想问一下在menuconfig里配置的data pin number该如何写？是根据板子的BSP中的映射（例如PA0, PA1... PH1 ---> PIN: 0, 1...63）来写，还是直接写例如PA0/PA9？
![image](https://user-images.githubusercontent.com/44700918/122673290-50112300-d202-11eb-8560-4ca65366e1b5.png)

**Comment by luhuadong** [comment]
> 作者你好，我想问一下在menuconfig里配置的data pin number该如何写？是根据板子的BSP中的映射（例如PA0, PA1... PH1 ---> PIN: 0, 1...63）来写，还是直接写例如PA0/PA9？ ![image](https://user-images.githubusercontent.com/44700918/122673290-50112300-d202-11eb-8560-4ca65366e1b5.png)

目前还是填数字，也许可以考虑修改一下，不知道会不会对其他架构的 BSP 有影响呢
